# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'IOSDouYuZB' do


  # Pods for IOSDouYuZB
pod "Alamofire"
pod "Kingfisher"
end
